apiVersion: v1
kind: List
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: mlbparks
      type: parksmap-backend
    name: mlbparks
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: mlbparks
      deploymentconfig: mlbparks
      type: parksmap-backend
    strategy:
      activeDeadlineSeconds: 21600
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
        post:
          failurePolicy: ignore
          execNewPod:
            containerName: busybox 
            command: [ "/usr/bin/curl", " http://mlbparks-f704-parks-dev.apps.na39.openshift.opentlc.com/ws/data/load/" ]
      type: Rolling
    template:
      metadata:
        labels:
          app: mlbparks
          deploymentconfig: mlbparks
          type: parksmap-backend
      spec:
        containers:
          - image: 'docker-registry.default.svc:5000/f704-parks-dev/mlbparks:0.0-0'
            imagePullPolicy: IfNotPresent
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /ws/healthz/
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 30
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            name: mlbparks
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /ws/healthz/
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 30
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
          - configMap:
              defaultMode: 420
              name: mlbparks-config
            name: mlbparks-mount
- apiVersion: v1
  data:
    APPNAME: "MLB Parks"
  kind: ConfigMap
  metadata:
    name: mlbparks-config
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: mlbparks
      type: parksmap-backend
    name: mlbparks
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: mlbparks
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: mlbparks
      type: parksmap-backend
    name: mlbparks
  spec:
    ports:
      - port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      app: mlbparks
      deploymentconfig: mlbparks
      type: parksmap-backend
    sessionAffinity: None
    type: ClusterIP
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      build: mlbparks
    name: mlbparks
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: 'mlbparks:latest'
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: 'jboss-eap70-openshift:1.7'
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5